### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by voji** [yehnan/SoftTimer#1]
I would like to use this timer on WemosD1 (retried) board, with ESP8266 chip. When i compile the project with arduino ide, i gave the following compiler error: 

libraries\SoftTimer-master\utility\EventBase.cpp: In constructor 'EventBase::EventBase()':

\SoftTimer-master\utility\EventBase.cpp:6:21: error: cast from 'EventBase*' to 'uint16_t {aka short unsigned int}' loses precision [-fpermissive]
     id = (uint16_t) this;
                     ^
exit status 1
Error compiling for board WeMos D1(Retired).

Possible fix: change the EventBase uint16_t id field type to intptr_t

**Comment by yehnan** [comment]
I think the error came from the size of object pointer is larger than 16 bits on your platform.

I don't take that into consideration when I wrote this library. And to fix, it needs also modify a lot of other code. I won't do it.

You're free to fork and modify to suit your need.

**Comment by mczerski** [comment]
#3 will solve the issue

**Comment by yehnan** [comment]
Thanks. Merged.
